# docker compose up
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=ChangeMe
