'use module'

import type { Metadata } from 'next'
import {
  ModuleExplorer,
  ModuleExplorerSkeleton,
} from '@/components/sidebar/module-explorer'
import { SolutionExplorer } from '@/components/sidebar/solution-explorer'
import { TaskExplorer } from '@/components/sidebar/task-explorer'
import { Sidebar, SidebarContent, SidebarHeader, SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ChartNoAxesGantt, File, List } from 'lucide-react'
import { Geist, Geist_Mono } from 'next/font/google'
import { Suspense } from 'react'
import getModuleExplorerData from '../actions/module-explorer-data'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function LeftSidebar() {
  const explorerPromise = getModuleExplorerData()

  return (
    <Sidebar variant="inset" side="left" className="overflow-auto">
      <Tabs defaultValue="explorer">
        <SidebarHeader className="p-0 border-b">
          <TabsList className="flex flex-row justify-start">
            <TabsTrigger value="explorer">
              <File className="h-4 w-4" />
            </TabsTrigger>
            <TabsTrigger value="tasks">
              <List className="h-4 w-4" />
            </TabsTrigger>
            <TabsTrigger value="solution">
              <ChartNoAxesGantt className="h-4 w-4" />
            </TabsTrigger>
          </TabsList>
        </SidebarHeader>

        <SidebarContent>
          <TabsContent value="explorer">
            <Suspense fallback={<ModuleExplorerSkeleton />}>
              <ModuleExplorer
                dataPromise={explorerPromise}
              />
            </Suspense>
          </TabsContent>
          <TabsContent value="tasks">
            <TaskExplorer />
          </TabsContent>
          <TabsContent value="solution">
            <SolutionExplorer />
          </TabsContent>
        </SidebarContent>
      </Tabs>
    </Sidebar>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <LeftSidebar />
          <SidebarInset>
            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  )
}
